services:
  db:
    image: postgres:15-alpine
    container_name: grigou_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: grigou_user
      POSTGRES_PASSWORD: grigou_password
      POSTGRES_DB: grigou_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grigou_user -d grigou_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
